import React, { useState } from 'react';
import { View, Text, StyleSheet, ScrollView, Alert } from 'react-native';
import { useApp } from '../context/AppContext';
import ScreenWrapper from '../components/ScreenWrapper';
import AppButton from '../components/AppButton';
import Input from '../components/Input';
import { colors } from '../constants/colors';

const LoginScreen = ({ navigation }) => {
    const { login, users } = useApp();
    const [mode, setMode] = useState('select'); // 'select' | 'signin' | 'signup'
    const [role, setRole] = useState(null); // 'provider' | 'worker'
    const [name, setName] = useState('');
    const [password, setPassword] = useState('');

    const handleRoleSelect = (selectedRole, authMode) => {
        setRole(selectedRole);
        setMode(authMode);
        setName('');
        setPassword('');
    };

    const handleSignIn = () => {
        if (!name || !password) {
            console.log('Missing name or password');
            return;
        }

        const internalRole = role === 'provider' ? 'requester' : 'worker';

        // Just log them in (password check would need backend)
        const success = login(internalRole, { name });
        if (success) {
            if (internalRole === 'worker') navigation.replace('WorkerHome');
            else navigation.replace('RequesterHome');
        }
    };

    const handleSignUp = () => {
        if (!name || !password) {
            console.log('Missing name or password');
            return;
        }

        if (password.length < 4) {
            console.log('Password too short');
            return;
        }

        const internalRole = role === 'provider' ? 'requester' : 'worker';

        // Check if user already exists
        const existingUser = users.find(u => u.name === name && u.role === internalRole);
        if (existingUser) {
            // User exists, just log them in instead
            const success = login(internalRole, { name });
            if (success) {
                if (internalRole === 'worker') navigation.replace('WorkerHome');
                else navigation.replace('RequesterHome');
            }
            return;
        }

        // Auto-generate ID when signing up
        const autoGeneratedId = `ID-${Date.now()}`;
        const autoGeneratedIdImage = 'verified';

        const success = login(internalRole, {
            name,
            nationalId: autoGeneratedId,
            idImage: autoGeneratedIdImage,
            password
        });

        if (success) {
            if (internalRole === 'worker') navigation.replace('WorkerHome');
            else navigation.replace('RequesterHome');
        }
    };

    // Role Selection Screen
    if (mode === 'select') {
        return (
            <ScreenWrapper>
                <View style={styles.center}>
                    <Text style={styles.title}>DailyGigs</Text>
                    <Text style={styles.subtitle}>Find or post short-term gigs</Text>

                    <View style={styles.roleSection}>
                        <Text style={styles.sectionLabel}>I want to Work</Text>
                        <AppButton title="Sign In" onPress={() => handleRoleSelect('worker', 'signin')} />
                        <AppButton title="Sign Up" variant="secondary" onPress={() => handleRoleSelect('worker', 'signup')} />
                    </View>

                    <View style={styles.divider} />

                    <View style={styles.roleSection}>
                        <Text style={styles.sectionLabel}>I need to Hire</Text>
                        <AppButton title="Sign In" onPress={() => handleRoleSelect('provider', 'signin')} />
                        <AppButton title="Sign Up" variant="secondary" onPress={() => handleRoleSelect('provider', 'signup')} />
                    </View>
                </View>
            </ScreenWrapper>
        );
    }

    // Sign In / Sign Up Form
    const isSignUp = mode === 'signup';
    const roleLabel = role === 'worker' ? 'Worker' : 'Provider';

    return (
        <ScreenWrapper>
            <ScrollView contentContainerStyle={styles.scroll}>
                <Text style={styles.title}>{isSignUp ? 'Create Account' : 'Welcome Back'}</Text>
                <Text style={styles.subtitle}>{roleLabel} {isSignUp ? 'Sign Up' : 'Sign In'}</Text>

                <Input
                    label="Full Name"
                    placeholder="Enter your name"
                    value={name}
                    onChangeText={setName}
                />

                <Input
                    label="Password"
                    placeholder="Enter password"
                    secureTextEntry
                    value={password}
                    onChangeText={setPassword}
                />

                {isSignUp && (
                    <View style={styles.infoBox}>
                        <Text style={styles.infoText}>
                            ✓ Your ID will be automatically verified upon sign up
                        </Text>
                    </View>
                )}

                <AppButton
                    title={isSignUp ? 'Create Account' : 'Sign In'}
                    onPress={isSignUp ? handleSignUp : handleSignIn}
                />

                <AppButton
                    title="Back"
                    variant="secondary"
                    onPress={() => setMode('select')}
                />
            </ScrollView>
        </ScreenWrapper>
    );
};

const styles = StyleSheet.create({
    center: {
        flex: 1,
        justifyContent: 'center',
    },
    scroll: {
        paddingVertical: 40,
    },
    title: {
        fontSize: 28,
        fontWeight: 'bold',
        color: colors.text,
        textAlign: 'center',
        marginBottom: 10,
    },
    subtitle: {
        fontSize: 16,
        color: colors.textSecondary,
        textAlign: 'center',
        marginBottom: 30,
    },
    roleSection: {
        marginBottom: 20,
    },
    sectionLabel: {
        fontSize: 18,
        fontWeight: '600',
        color: colors.text,
        marginBottom: 10,
        textAlign: 'center',
    },
    divider: {
        height: 1,
        backgroundColor: colors.border,
        marginVertical: 20,
    },
    infoBox: {
        backgroundColor: '#f0fdf4',
        padding: 12,
        borderRadius: 8,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: colors.success,
    },
    infoText: {
        color: colors.success,
        textAlign: 'center',
    }
});

export default LoginScreen;
